### ISSUE TITLE
Unable to use tf-eia-1.14-cpu

### ISSUE THREAD

**Issue by Andreachen0707** [aws/sagemaker-tensorflow-serving-container#90]
Hi,
When I tried to use tf-eia-1.14-cpu as my base image to deploy my model to sagemaker endpoints, an error occurs:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
worker.init_process()
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
super(GeventWorker, self).init_process()
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
self.load_wsgi()
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
self.wsgi = self.app.wsgi()
File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
return self.load_wsgiapp()
File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
return util.import_app(self.app_uri)
File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
__import__(module)
File "/sagemaker/python_service.py", line 23, in <module>
from proxy_client import GRPCProxyClient
File "/sagemaker/proxy_client.py", line 18, in <module>
import grpc

ModuleNotFoundError: No module named 'grpc'
```

Tried to add grpc in requirements.txt:
Error log as:
```
Collecting grpc (from -r /opt/ml/model/code/requirements.txt (line 3))
Downloading https://files.pythonhosted.org/packages/dd/63/e25fa1e7dbbd44ae4d2d5ceb1bfef517849c854795e73d01bfd3d250a8b1/grpc-0.3-19.tar.gz

ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0ml34koc/grpc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0ml34koc/grpc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
cwd: /tmp/pip-install-0ml34koc/grpc/
Complete output (10 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-0ml34koc/grpc/setup.py", line 7, in <module>
version_tuple = __import__('grpc').VERSION
File "/tmp/pip-install-0ml34koc/grpc/grpc/__init__.py", line 6, in <module>
from .rpc import *
File "/tmp/pip-install-0ml34koc/grpc/grpc/rpc.py", line 141
except OSError, ex:
^
SyntaxError: invalid syntax
----------------------------------------

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Traceback (most recent call last):
File "/sagemaker/serve.py", line 207, in _setup_gunicorn
subprocess.check_call(pip_install_cmd.split())
File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip3', 'install', '-r', '/opt/ml/model/code/requirements.txt']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/sagemaker/serve.py", line 373, in <module>
ServiceManager().start()
File "/sagemaker/serve.py", line 340, in start
self._setup_gunicorn()
File "/sagemaker/serve.py", line 210, in _setup_gunicorn
self._stop()
File "/sagemaker/serve.py", line 288, in _stop
os.kill(self._nginx.pid, signal.SIGQUIT)
AttributeError: 'NoneType' object has no attribute 'pid'
```

Other info:
model image: ```763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference-eia:1.14-cpu```

instance type: ``` ml.m4.xlarge``` with ```ml.eia1.medium```

Any help appreciated!

**Comment by laurenyu** [comment]
Thanks for using SageMaker! I've reached out to the team that builds the `763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference-eia:1.14-cpu` image to see if they have any insight.

**Comment by saimidu** [comment]
Hi @Andreachen0707 ,
You have done the right thing by adding grpc as a package to be installed in requirements.txt. However, please use `grpcio==1.25.0` instead of `grpc` in your requirements.txt.
[grpcio](https://pypi.org/project/grpcio/) is the official gRPC package for Python that is maintained by Google.
[grpc](https://pypi.org/project/grpc/) is an unofficial package.

**Comment by Andreachen0707** [comment]
Thank! Though I'm planning to use GPU instance instead, thanks for the help!
